let User,CustomErrorHandler;_a5f‍.x([["default",()=>_a5f‍.o]]);_a5f‍.w("../../models",[["User",["User"],function(v){User=v}]]);_a5f‍.w("../../services/CustomErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);


const userController = {
    async me(req, res, next){
        try{
            const user = await User.findOne({ _id: req.user._id }).select('-password -updatedAt -__v');
            if(!user){
                return next(CustomErrorHandler.notFound());
            }
            res.json(user);
        } catch(err){
            return next(err);
        }
    }
};

_a5f‍.d(userController);